name: Test

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  workflow_dispatch:

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:  
    name: Test
    strategy:
      fail-fast: false    
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.3.app
        
      - name: Test
        run: swift test

